name: checks

on:
  pull_request:
  push:
    branches: [master]

env:
  CI: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Use cached node_modules
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: node_modules+${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test
